set nocompatible

" Colors
syntax enable
let vars = ['init', 'editable', 'init_ui']
let colors = ['ff0000', '00ff00', '0000ff']
for var in vars
  execute 'syn keyword var_' . var var
  execute 'hi default var_' . var 'guifg=#' . remove(colors, 0)
endfor

" Highlight current line
set cursorline
" hi CursorLine   cterm=NONE ctermbg=black ctermfg=white guibg=black guifg=white

" Command completion
set wildmode=longest,list,full
set wildmenu

" Search
set incsearch
set ignorecase
set smartcase
set hlsearch
hi Search cterm=NONE ctermfg=black ctermbg=blue
hi Visual cterm=NONE ctermfg=black ctermbg=brown

" Navigation.
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Folding
set foldmethod=indent
set foldlevel=99
set showbreak=↪:w
noremap <Space> za<CR>

set listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮,trail:␣

" Line numbers
set rnu
set number
set list

" Search upwards until there's a tags file
set tags+=./tags

" Indentation
set expandtab
set colorcolumn=81
set shiftround  " Round indent to multiple of 'shiftwidth'
set smartindent " Do smart indenting when starting a new line
inoremap # X<BS>#
set autoindent  " Copy indent from current line, over to the new line

" Set the tab width
:au FileType python set tabstop=2
:au FileType python set shiftwidth=2

" Automatically remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" Go
" Some Linux distributions set filetype in /etc/vimrc.
" Clear filetype flags before changing runtimepath to force Vim to reload them.
filetype off
filetype plugin indent off
set runtimepath+=$GOROOT/misc/vim
filetype plugin indent on
syntax on

" Vundle
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required!
Bundle 'gmarik/vundle'

Bundle 'Valloric/YouCompleteMe'
Bundle 'scrooloose/syntastic'
Bundle "AutoTag"
Bundle 'scrooloose/nerdtree'
Bundle 'majutsushi/tagbar'
Bundle 'airblade/vim-gitgutter'
Bundle 'Yggdroot/indentLine'
Bundle 'tpope/vim-fugitive'
" Bundle 'Lokaltog/vim-powerline'
Bundle 'hdima/python-syntax'
Bundle 'christoomey/vim-tmux-navigator'
Bundle 'bling/vim-airline'

filetype plugin indent on     " required!
set tabstop=2
set shiftwidth=2

" Powerline
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs
set t_Co=256 " Explicitly tell Vim that the terminal supports 256 colors

let g:airline_powerline_fonts = 1
let g:airline_theme = 'wombat'

